name: netcut
description: Cut internet access for selected apps using a local VPN (no-root)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  go_router: ^17.0.1
  shared_preferences: ^2.5.4
  google_fonts: ^6.3.3
  flutter_neumorphic_plus: ^3.5.0
  permission_handler: ^12.0.1
  flutter_animate: ^4.5.2
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  lottie: ^3.3.2
  package_info_plus: ^8.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4



flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#2D5BFF"
  adaptive_icon_foreground: assets/icon/app_foreground.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/